services:
  jekyll:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ..:/site
    environment:
      - JEKYLL_ENV=development
